services:
  - type: web
    name: medimitra-backend
    runtime: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Djava.net.preferIPv4Stack=true -Xmx256m
      - key: DATABASE_URL
        value: jdbc:postgresql://db.thcfrsehlyxrpwvmwcdy.supabase.co:5432/postgres?sslmode=require&connectTimeout=120&socketTimeout=120&tcpKeepAlive=true&loginTimeout=120
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: Dheeraj@#123
      - key: JWT_SECRET
        value: 5v8y/B?E(H+MbQeThWmZq4t7w!z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVkYp
      - key: CORS_ALLOWED_ORIGINS
        value: https://medi-mitra-omega.vercel.app,https://*.vercel.app,http://localhost:5173,http://localhost:3000
      - key: SHOW_SQL
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 8080
