services:
  - type: web
    name: medimitra-backend
    runtime: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
      - key: DB_USERNAME
        value: postgres.thcfrsehlyxrpwvmwcdy
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://medi-mitra-omega.vercel.app,http://localhost:5173
      - key: SHOW_SQL
        value: false
      - key: PORT
        value: 8080
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE
        value: UTC
