services:
  - type: web
    name: medimitra-backend
    runtime: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://db.thcfrsehlyxrpwvmwcdy.supabase.co:5432/postgres?sslmode=require
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: Dheeraj@#123
      - key: JWT_SECRET
        value: 5v8y/B?E(H+MbQeThWmZq4t7w!z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVkY
      - key: CORS_ALLOWED_ORIGINS
        value: https://medi-mitra-omega.vercel.app,http://localhost:5173
      - key: SHOW_SQL
        value: false
      - key: PORT
        value: 8080
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE
        value: UTC
